doctrine:
    dbal:

        default_connection: default
        connections:
            default:
                driver: "pdo_pgsql"
                server_version: '12.3'
                charset: UTF-8
                default_table_options:
                    charset: UTF-8
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
#        auto_generate_proxy_classes: %kernel.debug%

        entity_managers:
            default:

                auto_mapping: true
                connection: default
                mappings:
                    App\Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App\Main
