doctrine:
    dbal:

        default_connection: default
        connections:
            default:
                server_version: '5.2'
                url: '%env(resolve:DATABASE_URL)%'
            mail:
                server_version: '5.2'
                url: '%env(resolve:DATABASE_URL_MAIL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
#        auto_generate_proxy_classes: %kernel.debug%

        entity_managers:
            default:

                auto_mapping: true
                connection: default
                mappings:
                    App\Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App\Main

            mail:

                connection: mail
                mappings:
                    App\Mail:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Mail'
                        prefix: 'App\Entity\Mail'
                        alias: App\Mail
