
cache:
  paths:
    - vendor/

stages:
  - build
  - test

variables:
  DB_HOST: mysql

  GIT_STRATEGY: fetch

  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 123
  POSTGRES_DB: cv_ludwig

build:
  stage: build
  script:
    - docker-compose up -d redis database
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

test:
  stage: test
  script:
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixture:load --no-interaction --env=test
    - php bin/phpunit
  dependencies:
    - build