image: registery.gitlab.silvain.eu/silvain.eu/cv-ludwig_php:base
cache:
  paths:
    - vendor/
    - node_modules/
    - public/build/


services:
  - redis:latest

stages:
  - compile
  - test
  - build
  - deploy

variables:
  DB_HOST: mysql
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

#compile:composer:
#  stage: compile
#  tags:
#    - docker
#  script:
#    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
#
#compile:nodejs:
#  before_script: []
#  image: node
#  stage: compile
#  tags:
#    - docker
#  script:
#    - yarn install --ignore-engines
#    - yarn encore dev
#
#phpunit:
#  stage: test
#  tags:
#    - docker
#  script:
#    #    - php bin/console doctrine:schema:update --force --env=test
#    #    - php bin/console doctrine:fixture:load --no-interaction --env=test
#    - php bin/phpunit
#  dependencies:
#    - compile:composer
#    - compile:nodejs
#
#docker-build-master:
#  before_script: []
#  tags:
#    - docker
#  # Official docker image.
#  image: docker:19.03.12
#  stage: build
#  services:
#    - docker:19.03.12-dind
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $CI_REGISTRY/silvain.eu/cv-ludwig_php:latest .
#    - docker push $CI_REGISTRY/silvain.eu/cv-ludwig_php:latest
#  only:
#    - master

deployment:production:ansible:
  tags:
    - docker
  services: []
  image: williamyeh/ansible:centos7
  stage: deploy
#  when: manual
  variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ansible_user: 'false'
  script:
    - ansible-playbook -i $CI_PROJECT_DIR/tools/ansible/deploy/inventory --extra-vars "ansible_ssh_pass=$ansible_password ansible_user=$ansible_user ansible_become_pass=$ansible_sudo_pass ansible_become_user=$ansible_become_user" --vault-password-file secret.sh $CI_PROJECT_DIR/tools/ansible/deploy/deploy.yml
  before_script:
    - echo -e "#/bin/bash\necho \"${ansible_vault}\";" > secret.sh
  after_script:
    - rm secret.sh