image: docker/compose:latest
cache:
  paths:
    - vendor/

stages:
  - build
  - test
variables:
  DB_HOST: mysql

  GIT_STRATEGY: fetch

  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 123
  POSTGRES_DB: cv_ludwig
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""


build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose up -d redis database web
#    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker run --rm --name composerinstall -v "$PWD":/var/www/app -w /var/www/app composer:1.4 install --no-dev --ignore-platform-reqs --no-suggest --no-progress --no-scripts --prefer-dist
    - ls vendor/

test:
  stage: test
  script:
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixture:load --no-interaction --env=test
    - php bin/phpunit
  dependencies:
    - build