image: registery.gitlab.silvain.eu/silvain.eu/cv-ludwig_php:base
cache:
  paths:
    - vendor/
    - node_modules/
    - public/build/


services:
  - redis:latest

stages:
  - compile
  - test
  - build

variables:
  DB_HOST: mysql
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

compile:composer:
  stage: compile
  tags:
    - docker
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

compile:nodejs:
  before_script: []
  image: node
  stage: compile
  tags:
    - docker
  script:
    - yarn install --ignore-engines
    - yarn encore dev

phpunit:
  stage: test
  tags:
    - docker
  script:
#    - php bin/console doctrine:schema:update --force --env=test
    #    - php bin/console doctrine:fixture:load --no-interaction --env=test
    - php bin/phpunit
  dependencies:
    - compile:composer
    - compile:nodejs

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master