image: php:7.4.0-fpm-buster
cache:
  paths:
    - vendor/

stages:
  - build
  - test
variables:
  DB_HOST: mysql

  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 123
  POSTGRES_DB: cv_ludwig
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apt-get update && apt-get install -y gnupg2 curl wget
  - docker-php-ext-install -j$(nproc) xml && docker-php-ext-install -j$(nproc) ctype && docker-php-ext-install -j$(nproc) zip unzip && docker-php-ext-install -j$(nproc) geoip && docker-php-ext-install -j$(nproc) mbstring && docker-php-ext-install -j$(nproc) readline && docker-php-ext-install -j$(nproc) uuid && docker-php-ext-install -j$(nproc) simplexml && docker-php-ext-install -j$(nproc) json && docker-php-ext-install -j$(nproc) phar && docker-php-ext-install -j$(nproc) curl && docker-php-ext-install -j$(nproc) memcached && docker-php-ext-install -j$(nproc) intl && docker-php-ext-install -j$(nproc) odbc && docker-php-ext-install -j$(nproc) opcache && docker-php-ext-install -j$(nproc) yaml && docker-php-ext-install -j$(nproc) cli && docker-php-ext-install -j$(nproc) dom && docker-php-ext-install -j$(nproc) fpm && docker-php-ext-install -j$(nproc) apcu && docker-php-ext-install -j$(nproc) pdo && docker-php-ext-install -j$(nproc) dev && docker-php-ext-install -j$(nproc) xml && docker-php-ext-install -j$(nproc) intl && docker-php-ext-install -j$(nproc) gd && docker-php-ext-install -j$(nproc) redis -y
build:
  stage: build
  tags:
    - docker
  script:
    - ls -l
    - docker-compose up -d redis database
#    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker run --rm --name composerinstall -v "$PWD":/var/www/app -w /var/www/app composer:1.4 install --no-dev --ignore-platform-reqs --no-suggest --no-progress --no-scripts --prefer-dist
    - ls vendor/

test:
  stage: test
  script:
    - docker-compose.exe exec web php bin/console doctrine:schema:update --force --env=test
    - docker-compose.exe exec web php bin/console doctrine:fixture:load --no-interaction --env=test
    - docker-compose.exe exec web php bin/phpunit
  dependencies:
    - build