version: '3.4'

services:
  web:
    image: registery.gitlab.silvain.eu/silvain.eu/cv-ludwig_php:base
    ports:
      - 8003:80
    volumes:
      - .:/var/www/web
      - ./vendor:/var/www/web/vendor
      - /var/www/web/var/cache
    command: bash -c "pwd && php bin/console cache:clear && service php7.4-fpm start && service php7.4-fpm status && /usr/sbin/apache2 -D FOREGROUND"
    tty: true
    links:
      - redis
      - mailcatcher
      - database
  redis:
    image: redis:5-alpine
    ports: [6379]
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1083:1080

  database:
    image: "mariadb" # use latest official postgres version
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql # persist data even


volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local
    name: pgadmin-data