version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - 8003:80
    depends_on:
      - php
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - php
      - yarn
  php:
    image: ghcr.io/silvainlud/cv-ludwig_php:base
    working_dir: /var/www/
    volumes:
      - ./var/www/node_modules
      - .:/var/www:cached
      - vendor:/var/www/vendor
      - var:/var/www/var/cache
    tty: true
    links:
      - redis
      - mailcatcher
      - database
  yarn:
    image: node
    working_dir: /var/www
    volumes:
      - node_modules:/var/www/node_modules
      - .:/var/www:delegated
      - vendor:/var/www/vendor
      - /var/www/var/cache
    command: /bin/sh -c "npm install && yarn watch"
#    ports:
#      - 9003:8080
#    command: /bin/sh -c "npm install && ./node_modules/.bin/encore dev-server --hot --port 8080 --host 0.0.0.0 --public localhost:9003"

  database:
    image: "mariadb" # use latest official postgres version
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql # persist data even

  redis:
    image: redis:5-alpine
    ports: [6379:6379]
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1083:1080



volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local
    name: pgadmin-data
  var:
  vendor:
  node_modules: