---
# vars file for ansistrano
web_user: www-data
user: ludwig


ansistrano_deploy_to: /var/www/cv/
ansistrano_deploy_via: git
ansistrano_current_via: "symlink"
ansistrano_allow_anonymous_stats: no

ansistrano_git_repo: "ssh://git@gitlab.silvain.eu:silvain.eu/cv-ludwig_php.git"
ansistrano_shared_paths: ["var/log", "var/cache", "var/spool"]
ansistrano_shared_files: [".env.local"]
ansistrano_ensure_shared_paths_exist: no
ansistrano_ensure_basedirs_shared_files_exist: no
ansistrano_keep_releases: 5

ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/before_symlink.yml"
ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/after_symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/end.yml"
ansistrano_rollback_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/end.yml"


